<?php

namespace gestCont\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    
    public function getMyContacts($name){
        $qb=$this
          ->createQueryBuilder('a')
          ->where('a.user1 = :name')
          ->setParameter('name',$name)
        ;
        return $qb;
  }
   public function getMyContactsName($name){
        $query = $this->_em->createQuery('SELECT a.user2 FROM gestContContactBundle:Contact a where a.user1 = :name');
        $query->setParameter('name', $name);
        $results=$query->getResult();
        $contacts=array();
        foreach ($results as $value){
           
                $contacts[]=$value['user2'];
           
        }
        return $contacts;
   }
}
