<?php

namespace gestCont\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    
    public function getListOfOthersUsers($user){
        $qb=$this
          ->createQueryBuilder('a')
          ->where('a.username != :name')
          ->setParameter('name',$user)
        ;
 
         return $qb->getQuery()->getResult();
  }
   public function getNotContacts(array $contacts,$user)
  {
    $qb=$this->createQueryBuilder('a');
    if(!empty($contacts)){
         $qb->where($qb->expr()->notIn('a.username',$contacts));
         $qb->andWhere('a.username != :name');
         $qb->setParameter('name',"".$user);
    }
    else{
         $qb->where('a.username != :name');
          $qb->setParameter('name',"".$user);
    }
   
     return $qb;
  }
  public function getInfos($user){
         $query = $this->_em->createQuery('SELECT a.username,a.email,a.adresse,a.telephone,a.site FROM gestContUserBundle:User a where a.username = :name');
         $query->setParameter('name', $user);
         return $query->getResult();
  }
}
